export type {
  PoemResponse as Poem,
  AuthorResponse as Author,
  GenreResponse as Genre,
  CommentResponse as Comment,
  PoemRequest as PoemRequestData,
  AuthorRequest as AuthorRequestData,
  GenreRequest as GenreRequestData,
  CommentRequest as CommentRequestData,
} from '@/types'
